# Active Profile 설정 (application-local.properties 로드)
spring.profiles.active=local

server.port=8181
spring.application.name=devAsk

# server encoding setting
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# Swagger
springdoc.swagger-ui.path: /swagger
springdoc.api-docs.path: /api-docs

# ??: View ??? ? DB ?? ??
spring.jpa.open-in-view=false

# JPA
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Database
#spring.datasource.hikari.maximum-pool-size=4
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/devask
spring.datasource.username=postgres
spring.datasource.password=1234

# HikariCP ??? ? ?? (???, ???)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=HikariPool-1